Update ci-harbor.yml

diff --git a/.github/workflows/ci-harbor.yml b/.github/workflows/ci-harbor.yml
--- a/.github/workflows/ci-harbor.yml
+++ b/.github/workflows/ci-harbor.yml
@@ -1,28 +1,44 @@
-name: CI-Harbor
+name: Build
 
 on:
   push:
     branches:
-      - master  # 또는 배포할 브랜치
+      - master
 
 jobs:
-  build-and-push:
-    runs-on: self-hosted  # Self-hosted runner 사용
+  build:
+    name: Build and analyze
+    runs-on: ubuntu-latest
+    
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
         with:
-          node-version: '22'
+          fetch-depth: 0  # 분석 정확도를 높이기 위해 shallow clone 비활성화
 
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v4
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-      - name: Login to Harbor
+      - name: SonarQube Quality Gate Check
+        id: sonarqube_quality_gate
+        uses: SonarSource/sonarqube-quality-gate-action@v1
+        timeout-minutes: 5
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+    # Quality Gate가 실패하면 전체 파이프라인 중단
+    outputs:
+      quality_gate_status: ${{ steps.sonarqube_quality_gate.outputs.quality_gate_status }}
+
+  check-quality-gate:
+    name: Check Quality Gate
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ needs.build.outputs.quality_gate_status != 'PASSED' }}
+    steps:
+      - name: Fail if Quality Gate fails
         run: |
-          docker login https://192.168.2.76:443 -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
-      - name: Build and push Docker images
-        run: |
-          BUILD_NUMBER=${{ github.run_number }} # GitHub Actions 빌드 번호
-          docker build -t 192.168.2.76:443/hama/hama_frontend:$BUILD_NUMBER .
-          docker push 192.168.2.76:443/hama/hama_frontend:$BUILD_NUMBER
+          echo "Quality Gate check failed. Stopping pipeline."
+          exit 1
